import { theme } from './src/styles/theme.js'

export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: [theme.font.family, 'system-ui', 'sans-serif'],
        display: [theme.font.displayFamily, 'Georgia', 'serif'],
      },
      fontSize: {
        micro: [theme.font.size.micro, { lineHeight: theme.font.lineHeight.body }],
        label: [theme.font.size.label, { lineHeight: theme.font.lineHeight.body }],
        body: [theme.font.size.body, { lineHeight: theme.font.lineHeight.body }],
        subheading: [theme.font.size.subheading, { lineHeight: theme.font.lineHeight.heading }],
        heading: [theme.font.size.heading, { lineHeight: theme.font.lineHeight.heading }],
        display: [theme.font.size.display, { lineHeight: theme.font.lineHeight.heading }],
      },
      fontWeight: {
        regular: theme.font.weight.regular,
        medium: theme.font.weight.medium,
        bold: theme.font.weight.bold,
      },
      colors: {
        primary: 'var(--lifeos-color-primary)',
        'primary-light': 'var(--lifeos-color-primary-light)',
        accent: 'var(--lifeos-color-accent)',
        'accent-ink': 'var(--lifeos-color-accent-ink)',
        'accent-light': 'var(--lifeos-color-accent-light)',
        success: 'var(--lifeos-color-success)',
        'success-light': 'var(--lifeos-color-success-light)',
        warning: 'var(--lifeos-color-warning)',
        'warning-light': 'var(--lifeos-color-warning-light)',
        danger: 'var(--lifeos-color-danger)',
        'danger-light': 'var(--lifeos-color-danger-light)',
        background: 'var(--lifeos-color-background)',
        surface: 'var(--lifeos-color-surface)',
        'surface-solid': 'var(--lifeos-color-surface-solid)',
        text: 'var(--lifeos-color-text)',
        muted: 'var(--lifeos-color-muted)',
        border: 'var(--lifeos-color-border)',
        'glass-border': 'var(--lifeos-color-glass-border)',
      },
      borderRadius: {
        sm: theme.radius.sm,
        md: theme.radius.md,
        lg: theme.radius.lg,
        xl: theme.radius.xl,
        full: theme.radius.full,
      },
      spacing: {
        xs: theme.spacing.xs,
        sm: theme.spacing.sm,
        md: theme.spacing.md,
        lg: theme.spacing.lg,
        xl: theme.spacing.xl,
        '2xl': theme.spacing['2xl'],
        '3xl': theme.spacing['3xl'],
      },
      boxShadow: {
        sm: theme.shadow.sm,
        md: theme.shadow.md,
        lg: theme.shadow.lg,
        glass: 'var(--lifeos-shadow-glass)',
      },
      backdropBlur: {
        glass: '24px',
      },
      zIndex: {
        base: String(theme.zIndex.base),
        aurora: String(theme.zIndex.aurora),
        card: String(theme.zIndex.card),
        header: String(theme.zIndex.header),
        'bottom-nav': String(theme.zIndex.bottomNav),
        'bottom-sheet': String(theme.zIndex.bottomSheet),
        modal: String(theme.zIndex.modal),
        toast: String(theme.zIndex.toast),
      },
      transitionDuration: {
        DEFAULT: theme.transition.duration,
      },
      transitionTimingFunction: {
        DEFAULT: theme.transition.easing,
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: 0 },
          '100%': { opacity: 1 },
        },
        'fade-rise': {
          '0%':   { opacity: 0, transform: 'translateY(12px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        'slide-up': {
          '0%': { transform: 'translateY(100%)', opacity: 0 },
          '100%': { transform: 'translateY(0)', opacity: 1 },
        },
        'scale-in': {
          '0%': { opacity: 0, transform: 'scale(0.96)' },
          '100%': { opacity: 1, transform: 'scale(1)' },
        },
        'toast-in': {
          '0%': { opacity: 0, transform: 'translateY(-8px)' },
          '100%': { opacity: 1, transform: 'translateY(0)' },
        },
        'fab-fan-in': {
          '0%':   { opacity: 0, transform: 'translateY(8px) scale(0.85)' },
          '100%': { opacity: 1, transform: 'translateY(0) scale(1)' },
        },
        'orb-drift-1': {
          '0%, 100%': { transform: 'translate(0px, 0px) scale(1)' },
          '50%':       { transform: 'translate(40px, -30px) scale(1.1)' },
        },
        'orb-drift-2': {
          '0%, 100%': { transform: 'translate(0px, 0px) scale(1)' },
          '50%':       { transform: 'translate(-50px, 25px) scale(1.05)' },
        },
        'orb-drift-3': {
          '0%, 100%': { transform: 'translate(0px, 0px) scale(1)' },
          '50%':       { transform: 'translate(30px, 40px) scale(0.95)' },
        },
        'blob-bob': {
          '0%, 100%': { transform: 'translateY(0) scale(1.012, 0.988)' },
          '50%':       { transform: 'translateY(-6px) scale(0.988, 1.012)' },
        },
        'blink': {
          '0%, 92%, 100%': { transform: 'scaleY(1)' },
          '94%, 96%':       { transform: 'scaleY(0.08)' },
        },
        'eye-gaze': {
          '0%, 70%, 100%': { transform: 'translateX(0)' },
          '78%, 86%':       { transform: 'translateX(2.5px)' },
        },
        'tuft-sway': {
          '0%, 100%': { transform: 'rotate(-4deg)' },
          '50%':       { transform: 'rotate(5deg)' },
        },
        'arm-wave': {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '50%':       { transform: 'rotate(18deg)' },
        },
        'shadow-pulse': {
          '0%, 100%': { transform: 'scaleX(1)', opacity: '0.12' },
          '50%':       { transform: 'scaleX(0.86)', opacity: '0.06' },
        },
        'slump-cycle': {
          '0%, 100%': { transform: 'translateY(0) scale(1, 1)' },
          '50%':       { transform: 'translateY(3px) scale(1.008, 0.984)' },
        },
        'puff-rise': {
          '0%, 5%':    { opacity: '0', transform: 'translate(0, 0) scale(0.7)' },
          '20%':       { opacity: '0.6', transform: 'translate(1px, -6px) scale(1)' },
          '60%':       { opacity: '0.4', transform: 'translate(4px, -20px) scale(1.15)' },
          '100%':      { opacity: '0', transform: 'translate(8px, -32px) scale(1.3)' },
        },
        'aura-pulse': {
          '0%, 100%': { opacity: 0.45, transform: 'scale(1)' },
          '50%':       { opacity: 0.7,  transform: 'scale(1.08)' },
        },
        'sparkle-twinkle': {
          '0%, 100%': { opacity: 0, transform: 'scale(0.6)' },
          '50%':       { opacity: 1, transform: 'scale(1)' },
        },
        'wiggle-ack': {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '25%':       { transform: 'rotate(-3deg) scale(1.04)' },
          '75%':       { transform: 'rotate(3deg) scale(1.04)' },
        },
        'body-stretch': {
          '0%, 100%': { transform: 'translateY(0) scale(1, 1)' },
          '40%':       { transform: 'translateY(-6px) scale(0.92, 1.12)' },
          '70%':       { transform: 'translateY(-2px) scale(1.02, 0.98)' },
        },
        'body-sneeze': {
          '0%, 100%': { transform: 'translate(0, 0) scale(1, 1)' },
          '15%':       { transform: 'translate(0, -3px) scale(1.04, 0.96)' },
          '30%':       { transform: 'translate(-3px, 1px) scale(0.95, 1.06)' },
          '50%':       { transform: 'translate(3px, 1px) scale(0.95, 1.06)' },
          '70%':       { transform: 'translate(-2px, 0) scale(1, 1)' },
        },
        'body-hiccup': {
          '0%, 100%': { transform: 'translateY(0) scale(1, 1)' },
          '30%':       { transform: 'translateY(-7px) scale(1.04, 0.94)' },
          '55%':       { transform: 'translateY(2px) scale(0.96, 1.04)' },
          '80%':       { transform: 'translateY(0) scale(1.01, 0.99)' },
        },
        'body-shimmy': {
          '0%, 100%': { transform: 'rotate(0deg)' },
          '20%':       { transform: 'rotate(-6deg)' },
          '50%':       { transform: 'rotate(6deg)' },
          '80%':       { transform: 'rotate(-4deg)' },
        },
        'body-surprised': {
          '0%, 100%': { transform: 'scale(1, 1)' },
          '30%':       { transform: 'scale(1.08, 1.08) translateY(-2px)' },
          '60%':       { transform: 'scale(0.98, 1.02)' },
        },
        'body-giggle': {
          '0%, 100%': { transform: 'translate(0, 0) rotate(0)' },
          '15%':       { transform: 'translate(-1px, 1px) rotate(-2deg)' },
          '30%':       { transform: 'translate(1px, -1px) rotate(2deg)' },
          '45%':       { transform: 'translate(-1px, 1px) rotate(-2deg)' },
          '60%':       { transform: 'translate(1px, -1px) rotate(2deg)' },
          '80%':       { transform: 'translate(0, 0) rotate(0)' },
        },
        'particle-rise': {
          '0%':   { opacity: '0', transform: 'translate(0, 4px) scale(0.6)' },
          '15%':  { opacity: '1', transform: 'translate(0, -2px) scale(1.05)' },
          '70%':  { opacity: '1', transform: 'translate(0, -22px) scale(1)' },
          '100%': { opacity: '0', transform: 'translate(0, -34px) scale(0.95)' },
        },
      },
      animation: {
        'fade-in': `fade-in 200ms ${theme.transition.easing}`,
        'fade-rise': `fade-rise 280ms ${theme.transition.easing} both`,
        'slide-up': `slide-up ${theme.transition.bottomSheet}`,
        'scale-in': `scale-in 200ms ${theme.transition.easing}`,
        'toast-in': `toast-in 220ms ${theme.transition.easing}`,
        'fab-fan-in': `fab-fan-in 220ms ${theme.transition.easing} both`,
        'orb-1': 'orb-drift-1 22s ease-in-out infinite',
        'orb-2': 'orb-drift-2 28s ease-in-out infinite',
        'orb-3': 'orb-drift-3 34s ease-in-out infinite',
        'blob-snooze':   'blob-bob 4.0s ease-in-out infinite',
        'blob-calm':     'blob-bob 3.0s ease-in-out infinite',
        'blob-alert':    'blob-bob 2.4s ease-in-out infinite',
        'blob-wired':    'blob-bob 1.8s ease-in-out infinite',
        'blink':         'blink 4.6s ease-in-out infinite',
        'eye-gaze':      'eye-gaze 9s ease-in-out infinite',
        'tuft-snooze':   'tuft-sway 5s ease-in-out infinite',
        'tuft-calm':     'tuft-sway 4s ease-in-out infinite',
        'tuft-alert':    'tuft-sway 3s ease-in-out infinite',
        'tuft-wired':    'tuft-sway 2.2s ease-in-out infinite',
        'arm-wave-slow': 'arm-wave 1.6s ease-in-out infinite',
        'arm-wave-fast': 'arm-wave 0.9s ease-in-out infinite',
        'shadow-snooze': 'shadow-pulse 4s ease-in-out infinite',
        'shadow-calm':   'shadow-pulse 3s ease-in-out infinite',
        'shadow-alert':  'shadow-pulse 2.4s ease-in-out infinite',
        'shadow-wired':  'shadow-pulse 1.8s ease-in-out infinite',
        'slump-snooze':  'slump-cycle 32s ease-in-out infinite',
        'slump-calm':    'slump-cycle 50s ease-in-out infinite',
        'slump-alert':   'slump-cycle 60s ease-in-out infinite',
        'slump-wired':   'slump-cycle 75s ease-in-out infinite',
        'puff-1':        'puff-rise 5s ease-out infinite',
        'puff-2':        'puff-rise 5s 1.7s ease-out infinite',
        'puff-3':        'puff-rise 5s 3.4s ease-out infinite',
        'aura-soft':     'aura-pulse 6s ease-in-out infinite',
        'aura-vivid':    'aura-pulse 3.5s ease-in-out infinite',
        'sparkle-1':     'sparkle-twinkle 2.4s ease-in-out infinite',
        'sparkle-2':     'sparkle-twinkle 2.4s 0.6s ease-in-out infinite',
        'sparkle-3':     'sparkle-twinkle 2.4s 1.2s ease-in-out infinite',
        'wiggle-ack':    `wiggle-ack 360ms ${theme.transition.easing}`,
        'body-stretch':    'body-stretch 1100ms ease-out 1',
        'body-sneeze':     'body-sneeze 900ms ease-in-out 1',
        'body-hiccup':     'body-hiccup 700ms ease-out 1',
        'body-shimmy':     'body-shimmy 1000ms ease-in-out 1',
        'body-surprised':  'body-surprised 700ms ease-out 1',
        'body-giggle':     'body-giggle 1100ms ease-in-out 1',
        'particle-rise':   'particle-rise 1100ms ease-out 1',
      },
    },
  },
  plugins: [],
}
